from __future__ import annotations

from pathlib import Path
import os
import uuid

from task5.common.config import protocol_id, run_path
from task5.common.io import checked_complete, complete, fresh_output, read_json, sha256, write_json
from task5.common.randomness import restore_rng, rng_state


def save_checkpoint(path, controller, optimizer, scheduler, shuffle_rng, meta):
    import torch
    path = Path(path)
    if path.exists():
        raise FileExistsError(f"Refusing to replace checkpoint: {path}")
    if any(w.router.pending.sum().item() for w in controller.wrappers.values() if w.router is not None):
        raise RuntimeError("Cannot checkpoint pending G4 update counts")
    staging = path.with_name(f".incomplete_{path.name}_{uuid.uuid4().hex}")
    with fresh_output(staging):
        torch.save({"routers": controller.state(), "optimizer": optimizer.state_dict(), "scheduler": scheduler.state_dict(),
                    "shuffle_rng": shuffle_rng.get_state(), "rng": rng_state(), "noise_rng": controller.noise_states()}, staging / "state.pt")
        meta = dict(meta, state_sha256=sha256(staging / "state.pt"))
        write_json(staging / "meta.json", meta)
        complete(staging, meta)
    # A failed staging directory remains visible for diagnosis, never as a valid candidate.
    if path.exists():
        raise FileExistsError(f"Checkpoint was concurrently created: {path}")
    os.rename(staging, path)


def restore_checkpoint(path, controller, optimizer=None, scheduler=None, shuffle_rng=None, expected=None):
    import torch
    meta = checked_complete(path)
    if expected is not None:
        for key, value in expected.items():
            if meta[key] != value:
                raise ValueError(f"Checkpoint {key} mismatch: {path}")
    # Only load checkpoints generated by this project from trusted local storage.
    state = torch.load(Path(path) / "state.pt", map_location="cpu", weights_only=False)
    controller.load_state(state["routers"])
    if optimizer is not None:
        optimizer.load_state_dict(state["optimizer"])
        scheduler.load_state_dict(state["scheduler"])
        shuffle_rng.set_state(state["shuffle_rng"])
        controller.load_noise_states(state["noise_rng"])
        restore_rng(state["rng"])
    return meta


def states(config, condition, run_id):
    if not condition.trainable:
        return [{"name": "static", "epoch": 0, "step": 0, "condition": condition.to_dict(), "protocol": protocol_id(config)}]
    directory = run_path(config, "train", condition, run_id) / "checkpoints"
    result = []
    for path in directory.iterdir():
        if path.is_dir() and not path.name.startswith("."):
            meta = read_json(path / "meta.json")
            if not (path / "complete.json").is_file():
                raise RuntimeError(f"Incomplete checkpoint: {path}")
            if meta["condition"] != condition.to_dict() or meta["protocol"] != protocol_id(config):
                raise ValueError("Checkpoint condition/protocol mismatch")
            result.append(meta)
    result.sort(key=lambda s: s["epoch"])
    if [s["epoch"] for s in result] != list(range(config["training"]["epochs"] + 1)):
        raise ValueError(f"Expected all 11 checkpoints before capture: {directory}")
    if any(b["step"] <= a["step"] for a, b in zip(result, result[1:])):
        raise ValueError("Checkpoint steps are not strictly increasing")
    return result


def load_for_capture(config, condition, run_id, state, controller, header):
    if condition.trainable:
        path = run_path(config, "train", condition, run_id) / "checkpoints" / state["name"]
        restore_checkpoint(path, controller, expected={"condition": condition.to_dict(), "protocol": protocol_id(config), "input_header": header})
